backend:
  name: github
  repo: tawakalisme/qblt-blog

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Post"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "portfolios"
    label: "Portfolio"
    folder: "portfolios"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Dribbble", name: "dribbble-link", widget: "string" }
      - { label: "Font", name: "font", widget: "string" }
      - { label: "Platform", name: "platform", widget: "string" }
      - { label: "Tools", name: "tools", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Images", name: "images", widget: "markdown" }
